// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwww555-zliE3Xe6kkJB4ScSUHhrQTTA',
    appId: '1:728487409308:web:ec5ff5060cd7e8a91f5f59',
    messagingSenderId: '728487409308',
    projectId: 'chat-app-37f3c',
    authDomain: 'chat-app-37f3c.firebaseapp.com',
    storageBucket: 'chat-app-37f3c.appspot.com',
    measurementId: 'G-D8GRNM35BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDg1tRTyZ7qCZ1o1Yh5u6JDJIjHxF85Qw',
    appId: '1:728487409308:android:f1c193f3950a38381f5f59',
    messagingSenderId: '728487409308',
    projectId: 'chat-app-37f3c',
    storageBucket: 'chat-app-37f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3T8d4yHydQ0kIyzoKValusu8VH2Qf8tc',
    appId: '1:728487409308:ios:425f839eca4836341f5f59',
    messagingSenderId: '728487409308',
    projectId: 'chat-app-37f3c',
    storageBucket: 'chat-app-37f3c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
